# Placeholder. The real file is generated by nixos-anywhere on first install
# (`nixos-generate-config --no-filesystems --root /mnt`) and committed back by
# the install workflow (or by the user). Until then, this stub keeps `nix flake
# check` happy.
{ modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];
  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ ];
  nixpkgs.hostPlatform = "x86_64-linux";
}
